language: node_js

node_js:
  - 8.9.1

# install:
  # - brew install ccache
  # - brew install libpng
#  - export PATH="/usr/local/opt/ccache/libexec:$PATH"

script:
  - npm run build:dll
  - npm run build

# before_install:
#   - yarn

install:
  - yarn

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
    # - $HOME/Library/Caches/Homebrew
after_success:
    # - curl -k -T build sftp://${USER_NAME}:${USER_PASSWORD}@blog.godotdotdot.com/home/test/
    - curl -k -T build/ -u ${USER_NAME}:${USER_PASSWORD} ftp://www.alismarty.com/didacampus/
# os: osx
# deploy:
#   provider: pages
#   skip-cleanup: false # prevent Travis CI from resetting your working directory and deleting all changes made during the build
#   github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#   keep-history: false
#   local_dir: build
#   on:
#     branch: master

branches:
  only:
  - master
  - /^dev-.*$/